### ISSUE TITLE
Goroutine leak?

### ISSUE THREAD

**Issue by sethgrid** [afex/hystrix-go#73]
Hi!
If a function times out, ala:
https://github.com/afex/hystrix-go/blob/master/hystrix/hystrix.go#L160-L165

Then this would block, causing a leaked goroutine:
https://github.com/afex/hystrix-go/blob/master/hystrix/hystrix.go#L97

Yeah?

**Comment by afex** [comment]
thanks for the report.  i'll get this addressed and add a test

**Comment by cfchou** [comment]
Hi @sethgrid,

If I'm reading you right, I believe [https://github.com/afex/hystrix-go/blob/master/hystrix/hystrix.go#L97](url) shouldn't block because `cmd.finished` is a [buffered chan](https://github.com/afex/hystrix-go/blob/master/hystrix/hystrix.go#L59).

**Comment by sethgrid** [comment]
Ah, a buffered chan should handle that, as long as the buffer does not fill. :)

**Comment by cfchou** [comment]
My observation is that `cmd.finished` doesn't fill. Because `cmd` is a local variable and is accessed by two goroutines created in the same scope. Only one of them at [L97](https://github.com/afex/hystrix-go/blob/master/hystrix/hystrix.go#L97) writes once to `cmd.finished`.

I hope I  don't miss anything though.

**Comment by sethgrid** [comment]
Makes sense; sorry for the false alarm!

**Comment by smnalex** [comment]
@sethgrid @afex should this issue be closed?

**Comment by sethgrid** [comment]
Yes. I should have done that; my bad!
